
import nbformat as nbf

def generate_notebook(report, target_col):
    """Generate a Jupyter Notebook documenting the AutoML process."""
    nb = nbf.v4.new_notebook()
    
    # 1. Title & Imports
    nb['cells'].append(nbf.v4.new_markdown_cell(f"""# 🤖 AutoML Report: Predicting '{target_col}'
**Generated by Data Science Master System**
    """))
    
    nb['cells'].append(nbf.v4.new_code_cell("""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, r2_score, mean_absolute_error

%matplotlib inline"""))
    
    # 2. Data Loading (Simulated for the notebook user)
    nb['cells'].append(nbf.v4.new_markdown_cell("## 1. Data Loading\nLoad your dataset here."))
    nb['cells'].append(nbf.v4.new_code_cell(f"""# Replace 'data.csv' with your actual file path
# df = pd.read_csv('data.csv')
# df.head()"""))

    # 3. Data Cleaning Stats
    cleaning_text = "\n".join([f"- {step}" for step in report['cleaning_steps']])
    nb['cells'].append(nbf.v4.new_markdown_cell(f"## 2. Automated Cleaning Steps Applied\nThe following steps were automatically applied to clean the data:\n\n{cleaning_text}"))
    
    # 4. Modeling Logic
    model_type = report['model_type']
    nb['cells'].append(nbf.v4.new_markdown_cell(f"## 3. Model Training ({model_type})\nWe used a Random Forest model for this task."))
    
    if model_type == "Classification":
        model_code = """model = RandomForestClassifier(n_estimators=100, random_state=42)
# model.fit(X_train, y_train)"""
    else:
        model_code = """model = RandomForestRegressor(n_estimators=100, random_state=42)
# model.fit(X_train, y_train)"""
        
    nb['cells'].append(nbf.v4.new_code_cell(model_code))
    
    # 5. Results
    metrics_text = "\n".join([f"- **{k}**: {v}" for k, v in report['metrics'].items()])
    nb['cells'].append(nbf.v4.new_markdown_cell(f"## 4. Model Performance\nAchieved metrics:\n\n{metrics_text}"))
    
    # 6. Feature Importance
    top_features = report['importance'].head(5)['Feature'].tolist()
    nb['cells'].append(nbf.v4.new_markdown_cell(f"## 5. Top Influencing Factors\nThe most important features found were:\n" + "\n".join([f"{i+1}. {f}" for i, f in enumerate(top_features)])))
    
    return nbf.writes(nb)
