"""
Jupyter Notebook Generator - Creates reproducible analysis notebooks
"""

import json
from typing import Dict, Any, List


def generate_notebook(
    target_col: str,
    problem_type: str,
    feature_importance: List[str],
    metrics: Dict[str, Any],
    cleaning_steps: List[str],
    lang: str = 'ar'
) -> str:
    """
    Generate a comprehensive Jupyter Notebook with all analysis code.
    
    Args:
        target_col: Target column name
        problem_type: 'classification' or 'regression'
        feature_importance: List of top features
        metrics: Model metrics
        cleaning_steps: List of cleaning steps performed
        lang: Language for comments
    
    Returns:
        JSON string of notebook content
    """
    
    notebook = {
        "cells": [],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.9.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    
    def add_markdown(text: str):
        notebook["cells"].append({
            "cell_type": "markdown",
            "metadata": {},
            "source": text.split("\n")
        })
    
    def add_code(code: str):
        notebook["cells"].append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": code.split("\n")
        })
    
    # Title
    if lang == 'ar':
        add_markdown(f"""# 🤖 تحليل البيانات بالذكاء الاصطناعي
        
**المتغير المستهدف:** `{target_col}`  
**نوع المشكلة:** {'تصنيف' if problem_type == 'classification' else 'انحدار (توقع قيمة رقمية)'}

هذا الكود تم توليده تلقائياً بواسطة AI Expert ويمكنك إعادة تشغيله وتعديله.
""")
    else:
        add_markdown(f"""# 🤖 AI-Powered Data Analysis

**Target Variable:** `{target_col}`  
**Problem Type:** {problem_type.title()}

This code was auto-generated by AI Expert and can be re-run and modified.
""")
    
    # Imports
    if lang == 'ar':
        add_markdown("## 1. 📦 استيراد المكتبات")
    else:
        add_markdown("## 1. 📦 Import Libraries")
    
    add_code("""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, r2_score, classification_report, mean_squared_error
import warnings
warnings.filterwarnings('ignore')

# For better plots
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)
%matplotlib inline""")
    
    # Load Data
    if lang == 'ar':
        add_markdown("## 2. 📂 تحميل البيانات")
    else:
        add_markdown("## 2. 📂 Load Data")
    
    add_code("""# Replace with your file path
# استبدل المسار بمسار ملفك - يفضل استخدام ملف النتائج الذي قمت بتحميله
# Load the cleaned data from the Excel report (Sheet: Clean_Data)
try:
    df = pd.read_excel('AI_Expert_Results.xlsx', sheet_name='Clean_Data' if 'Clean_Data' in pd.ExcelFile('AI_Expert_Results.xlsx').sheet_names else 0)
except FileNotFoundError:
    # Fallback to CSV if you have it
    df = pd.read_csv('your_data.csv')

print(f"Data Shape: {df.shape}")
df.head()""")
    
    # EDA
    if lang == 'ar':
        add_markdown("## 3. 🔍 استكشاف البيانات")
    else:
        add_markdown("## 3. 🔍 Exploratory Data Analysis")
    
    add_code("""# Basic Info
print("=== Dataset Info ===")
print(df.info())
print("\\n=== Statistical Summary ===")
df.describe()""")
    
    add_code("""# Missing Values
missing = df.isnull().sum()
if missing.sum() > 0:
    print("Missing Values:")
    print(missing[missing > 0])
else:
    print("No missing values!")""")
    
    # Cleaning
    if lang == 'ar':
        add_markdown(f"""## 4. 🧹 تنظيف البيانات
        
الخطوات التي تم تنفيذها:
{chr(10).join(['- ' + step for step in cleaning_steps])}
""")
    else:
        add_markdown(f"""## 4. 🧹 Data Cleaning

Steps performed:
{chr(10).join(['- ' + step for step in cleaning_steps])}
""")
    
    add_code(f"""# Define target
target = '{target_col}'

# Remove duplicates
df = df.drop_duplicates()

# Handle missing values
# Numeric: fill with median
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Categorical: fill with mode
cat_cols = df.select_dtypes(exclude=np.number).columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Data cleaned!")
print(f"Final shape: {{df.shape}}")""")
    
    # Encoding
    if lang == 'ar':
        add_markdown("## 5. 🏷️ ترميز البيانات الفئوية")
    else:
        add_markdown("## 5. 🏷️ Encode Categorical Variables")
    
    add_code(f"""# Encode categorical columns
label_encoders = {{}}
for col in df.select_dtypes(include='object').columns:
    if col != target:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        label_encoders[col] = le

# Encode target if categorical
if df[target].dtype == 'object':
    target_le = LabelEncoder()
    df[target] = target_le.fit_transform(df[target])
    print(f"Target classes: {{target_le.classes_}}")""")
    
    # Modeling
    if lang == 'ar':
        add_markdown("## 6. 🧠 بناء النموذج")
    else:
        add_markdown("## 6. 🧠 Build Model")
    
    model_class = "RandomForestClassifier" if problem_type == 'classification' else "RandomForestRegressor"
    
    add_code(f"""# Prepare data
X = df.drop(columns=[target])
y = df[target]

# Scale features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# Train model
model = {model_class}(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

print("Model trained successfully!")""")
    
    # Evaluation
    if lang == 'ar':
        add_markdown("## 7. 📊 تقييم النموذج")
    else:
        add_markdown("## 7. 📊 Evaluate Model")
    
    if problem_type == 'classification':
        add_code("""# Predictions
y_pred = model.predict(X_test)

# Metrics
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2%}")
print("\\nClassification Report:")
print(classification_report(y_test, y_pred))""")
    else:
        add_code("""# Predictions
y_pred = model.predict(X_test)

# Metrics
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")""")
    
    # Feature Importance
    if lang == 'ar':
        add_markdown("## 8. 🔥 أهمية الميزات")
    else:
        add_markdown("## 8. 🔥 Feature Importance")
    
    add_code("""# Feature Importance
importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)

# Plot
plt.figure(figsize=(10, 6))
plt.barh(importance_df['Feature'][:10], importance_df['Importance'][:10])
plt.xlabel('Importance')
plt.title('Top 10 Feature Importance')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

importance_df.head(10)""")
    
    # Predictions
    if lang == 'ar':
        add_markdown("## 9. 🎯 التوقع على بيانات جديدة")
    else:
        add_markdown("## 9. 🎯 Predict on New Data")
    
    add_code("""# Load new data
# new_data = pd.read_csv('new_data.csv')

# Apply same preprocessing
# new_data_scaled = scaler.transform(new_data)

# Make predictions
# predictions = model.predict(new_data_scaled)

print("Ready for predictions!")""")
    
    # Save Model
    if lang == 'ar':
        add_markdown("## 10. 💾 حفظ النموذج")
    else:
        add_markdown("## 10. 💾 Save Model")
    
    add_code("""import joblib

# Save model
joblib.dump(model, 'trained_model.pkl')

# Save scaler
joblib.dump(scaler, 'scaler.pkl')

# Save encoders
joblib.dump(label_encoders, 'encoders.pkl')

print("Model and preprocessors saved!")

# To load later:
# model = joblib.load('trained_model.pkl')""")
    
    return json.dumps(notebook, indent=2, ensure_ascii=False)


def get_notebook_bytes(notebook_json: str) -> bytes:
    """Convert notebook JSON to bytes for download."""
    return notebook_json.encode('utf-8')
